# --- BIẾN MÔI TRƯỜNG MỚI CHO MONGODB ---
MONGO_HOST: localhost
MONGO_PORT: 27017
MONGO_DB: angulartts-db  # Updated to match docker-compose
MONGO_USERNAME: 
MONGO_PASSWORD: 
MONGO_AUTH_DB: admin

# --- CÁC BIẾN CHO TOKEN VẪN GIỮ NGUYÊN ---
ACCESS_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/access-token-private.key"
ACCESS_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/access-token-public.key"
REFRESH_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/refresh-token-private.key"
REFRESH_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/refresh-token-public.key"